AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourceCodeBucket:
    Type: String
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref Name
      TopicName: !Ref Name